import {INITIAL,fresh,metrics,order,nextDay} from './engine.js';
const $=id=>document.getElementById(id), fmt=n=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:0}), pct=n=>(n>=0?'+':'')+n.toFixed(2)+'%';
let state=fresh(),selected=INITIAL[0].ticker,side='buy',sound=true,mode='line',busy=false,toastTimer,resetType='portfolio';
const STORAGE='kkeolmusae-glass-v1';
try{const saved=JSON.parse(localStorage.getItem(STORAGE));if(saved&&saved.stocks?.length===6&&Number.isFinite(saved.appliedCoins)&&saved.holdings&&INITIAL.every(x=>saved.stocks.some(y=>y.ticker===x.ticker&&Number.isFinite(y.price)&&y.price>=0))&&Object.entries(saved.holdings).every(([t,h])=>INITIAL.some(x=>x.ticker===t)&&Number.isInteger(h.shares)&&h.shares>0&&Number.isFinite(h.avgPrice)&&h.avgPrice>=0)){state={...fresh(),...saved};}sound=localStorage.getItem('kkeolmusae-sound')!=='off';}catch{}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state));}catch{toast('이 브라우저에서는 기록을 저장할 수 없어요.');}}
function toast(text){$('toastText').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3600);}
let audio;
function playSound(kind='tap'){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();const notes=kind==='buy'?[523.25,659.25,783.99]:kind==='sell'?[783.99,659.25,523.25]:kind==='error'?[220,196]:[740];notes.forEach((frequency,i)=>{const oscillator=audio.createOscillator(),gain=audio.createGain(),start=audio.currentTime+i*.085;oscillator.type='sine';oscillator.frequency.setValueAtTime(frequency,start);gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(kind==='tap'?.018:.055,start+.012);gain.gain.exponentialRampToValueAtTime(.0001,start+.23);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start(start);oscillator.stop(start+.25);});}catch{}}
document.addEventListener('click',e=>{if(e.target.closest('button')&&!e.target.closest('#submitOrder')&&!e.target.closest('#sound'))playSound();});
function stock(){return state.stocks.find(x=>x.ticker===selected);}
function quantity(){return Math.floor(Number($('quantity').value));}
function renderOrder(){const s=stock(),m=metrics(state);$('orderName').textContent=s.name;$('orderTicker').textContent=s.ticker;$('orderAmount').textContent=fmt(Math.max(0,quantity()||0));$('available').textContent=fmt(side==='buy'?m.available:state.holdings[selected]?.shares||0);$('amountLabel').textContent=side==='buy'?'이번에 투자할 코인':'이번에 회수할 코인';$('availableLabel').textContent=side==='buy'?'추가로 투자 가능':'회수 가능한 투자 코인';$('submitOrder').textContent=side==='buy'?'코인 투자하기':'코인 회수하기';$('submitOrder').classList.toggle('sell',side==='sell');for(const which of ['buy','sell']){$(which+'Tab').classList.toggle('selected',side===which);$(which+'Tab').setAttribute('aria-pressed',String(side===which));}}
function render(){const s=stock(),m=metrics(state);$('greeting').textContent=state.nickname;$('profileButton').textContent=state.nickname+'의 계정';$('coins').textContent=fmt(state.appliedCoins);$('availableSummary').textContent=fmt(m.available);$('totalReturn').innerHTML=(m.returns>=0?'+':'')+m.returns.toFixed(2)+'<span>%</span>';$('totalReturn').className='metric '+(m.returns>=0?'positive':'negative');$('returnTag').textContent=m.returns>=0?'수익 구간':'손실 구간';$('dayLabel').textContent='SIMULATION / DAY '+String(state.day+1).padStart(2,'0');$('stockName').textContent=s.name;$('stockTicker').textContent=s.ticker;$('price').innerHTML=fmt(s.price)+'<small> KRW</small>';$('change').innerHTML=pct(s.change)+' <small>오늘</small>';$('change').className=s.change>=0?'positive':'negative';$('chart').setAttribute('aria-label',`${s.name} 모의 가격 차트, 현재 ${fmt(s.price)}원, ${pct(s.change)}. 좌우 방향키로 탐색.`);$('sound').textContent=sound?'켜짐':'꺼짐';$('sound').setAttribute('aria-pressed',String(sound));renderOrder();renderHoldings();renderWatch();renderOutcomeCoin();}
function renderHoldings(){const positions=state.stocks.filter(x=>state.holdings[x.ticker]?.shares>0);$('positionCount').textContent=String(positions.length).padStart(2,'0');if(!positions.length){$('holdings').innerHTML='<div class="empty-holdings"><div><strong>첫 번째 투자를 기다리고 있어요.</strong><p>관심 있는 종목을 선택하고, 가볍게 시작해 보세요.</p></div><button id="browse">종목 둘러보기</button></div>';$('browse').onclick=()=>{$('market').scrollIntoView({behavior:'smooth'});};return;}$('holdings').innerHTML='<div class="table-wrap"><table><thead><tr><th>종목</th><th>투자 코인</th><th>수익률</th></tr></thead><tbody>'+positions.map(s=>{const h=state.holdings[s.ticker],r=h.avgPrice>0?(s.price-h.avgPrice)/h.avgPrice*100:0;return `<tr><td><button data-select="${s.ticker}">${s.name}<small>${s.ticker}</small></button></td><td>${fmt(h.shares)} 코인</td><td class="${r>=0?'positive':'negative'}">${pct(r)}</td></tr>`;}).join('')+'</tbody></table></div>';$('holdings').querySelectorAll('[data-select]').forEach(el=>el.onclick=()=>selectStock(el.dataset.select));}
function renderWatch(){$('watchlist').innerHTML=state.stocks.map((s,i)=>{const points=Array.from({length:20},(_,j)=>`${j*2.4},${18-j*(s.change>=0?.55:-.12)-Math.sin(j*1.6+i)*4}`).join(' ');return `<button class="watch-row ${s.ticker===selected?'selected':''}" data-ticker="${s.ticker}" aria-pressed="${s.ticker===selected}"><span><strong>${s.name}</strong><small>${s.ticker}</small></span><svg viewBox="0 0 48 27" aria-hidden="true"><polyline points="${points}" fill="none" stroke="${s.change>=0?'#8fe9cf':'#ef93a3'}" stroke-width="1.2"/></svg><span class="${s.change>=0?'positive':'negative'}">${pct(s.change)}</span></button>`;}).join('');$('watchlist').querySelectorAll('button').forEach(el=>el.onclick=()=>selectStock(el.dataset.ticker));}
function selectStock(ticker){selected=ticker;$('quantity').value=1;render();rebuildChart();}
$('buyTab').onclick=()=>{side='buy';renderOrder();};$('sellTab').onclick=()=>{side='sell';renderOrder();};$('quantity').oninput=renderOrder;$('decrease').onclick=()=>{$('quantity').value=Math.max(1,(quantity()||1)-1);renderOrder();};$('increase').onclick=()=>{$('quantity').value=(quantity()||0)+1;renderOrder();};document.querySelectorAll('[data-amount]').forEach(el=>el.onclick=()=>{const max=side==='buy'?metrics(state).available:state.holdings[selected]?.shares||0;$('quantity').value=el.dataset.amount==='max'?max:Number(el.dataset.amount);renderOrder();});
$('submitOrder').onclick=()=>{if(busy)return;try{state=order(state,selected,side,$('quantity').value);save();render();playSound(side);toast(`${stock().name}${side==='buy'?'에':'에서'} ${fmt(quantity())}코인을 ${side==='buy'?'투자':'회수'}했어요.`);}catch(e){playSound('error');toast(e.message);}};
$('sound').onclick=()=>{sound=!sound;try{localStorage.setItem('kkeolmusae-sound',sound?'on':'off');}catch{}render();if(sound)playSound('buy');};$('help').onclick=()=>toast('코인 1개는 모의 1주입니다. 주문은 가상 시세로 즉시 체결됩니다.');$('favorite').onclick=()=>toast(stock().name+' 관심 종목에 추가했어요.');$('allStocks').onclick=()=>toast('더 많은 종목이 곧 추가돼요.');$('tipMore').onclick=()=>toast('투자 팁은 매일 새롭게 업데이트돼요.');$('closeToast').onclick=()=>$('toast').hidden=true;
function openProfile(){$('nickname').value=state.nickname;$('startingCoins').value=state.startingCoins;$('profileDialog').showModal();}
$('profileButton').onclick=openProfile;$('closeProfile').onclick=()=>$('profileDialog').close();$('profileForm').onsubmit=e=>{e.preventDefault();const nickname=$('nickname').value.trim().slice(0,12),coins=Math.floor(Number($('startingCoins').value));if(!nickname||!Number.isFinite(coins)||coins<0)return toast('닉네임과 0 이상의 시작 코인을 입력해 주세요.');state={...state,nickname,startingCoins:coins,appliedCoins:coins,day:0};save();render();$('profileDialog').close();toast('프로필과 보유 코인을 저장했어요.');};
function askReset(type){resetType=type;$('confirmTitle').textContent=type==='all'?'계정 전체 리셋':'포트폴리오 초기화';$('confirmText').textContent=type==='all'?'모든 모의투자 기록을 지우고 시작 코인을 다시 설정할까요?':'투자한 종목을 모두 초기화할까요?';$('confirmDialog').showModal();}
$('resetPortfolio').onclick=()=>askReset('portfolio');$('fullReset').onclick=()=>askReset('all');$('cancelReset').onclick=()=>$('confirmDialog').close();$('confirmReset').onclick=()=>{if(resetType==='all'){state=fresh();state.startingCoins=0;state.appliedCoins=0;selected=INITIAL[0].ticker;save();render();rebuildChart();$('profileDialog').close();openProfile();$('nickname').value='';$('startingCoins').value='';}else{state.holdings={};state.cash=1e8;save();render();toast('가상 포트폴리오를 초기화했어요.');}$('confirmDialog').close();};
$('nextDay').onclick=()=>{if(busy)return;busy=true;$('nextDay').disabled=true;$('submitOrder').disabled=true;$('dayOverlay').hidden=false;$('dayOverlay').setAttribute('role','status');document.querySelector('main').inert=true;document.querySelector('header').inert=true;setTimeout(()=>{state=nextDay(state);save();busy=false;document.querySelector('main').inert=false;document.querySelector('header').inert=false;$('nextDay').disabled=false;$('submitOrder').disabled=false;$('dayOverlay').hidden=true;render();rebuildChart();showDayResult();},5000);};
document.querySelectorAll('nav a').forEach(el=>el.onclick=()=>{document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a===el));});
// Presentation samples animate independently; account valuation changes only on nextDay.
const canvas=$('chart'),ctx=canvas.getContext('2d');let samples=[],previous=[],transitionStart=0,hover=-1,w=0,h=0,frame=0,lastPaint=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
function makeSamples(){const s=stock(),seed=state.stocks.findIndex(x=>x.ticker===selected)+2,n=90;const shape=Array.from({length:n},(_,i)=>{const drift=(i/(n-1)-.48)*(s.change>=0?.11:-.07);return 1+drift+Math.sin(i*.25+seed)*.022+Math.sin(i*.92+seed*2)*.008+Math.sin(i*2.81+seed)*.006;});return shape.map((x,i)=>({value:s.price*(x/shape.at(-1)),volume:12+Math.abs(Math.sin(i*7.123+seed))*43+Math.abs(Math.sin(i*3.7))*20}));}
function rebuildChart(){previous=samples.length?samples:makeSamples();samples=makeSamples();transitionStart=performance.now();hover=-1;$('chartTooltip').hidden=true;if(reduced.matches)draw(performance.now());}
function resize(){const box=canvas.getBoundingClientRect();w=box.width;h=box.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw(performance.now());}
function draw(time){if(!samples.length||!w)return;ctx.clearRect(0,0,w,h);const padL=10,padR=65,padT=22,padB=30,plotW=w-padL-padR,priceH=h-95;const ease=reduced.matches?1:Math.min(1,(time-transitionStart)/700),t=1-Math.pow(1-ease,3);const prices=samples.map((p,i)=>{const old=previous[i]?.value??p.value;const wave=reduced.matches?0:Math.sin(time*.0018+i*.47)*stock().price*.0012*Math.sin(i/(samples.length-1)*Math.PI);return old+(p.value-old)*t+wave;});let min=Math.min(...prices),max=Math.max(...prices);const spread=Math.max(max-min,stock().price*.03,1);min-=spread*.2;max+=spread*.2;const x=i=>padL+i/(samples.length-1)*plotW,y=value=>padT+(max-value)/(max-min)*priceH;const color=stock().change>=0?'#8fe9cf':'#ef93a3';ctx.font='9px "DM Sans", sans-serif';ctx.textBaseline='middle';
for(let i=0;i<5;i++){const yy=padT+i*priceH/4;ctx.strokeStyle='#c5d6df0c';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(padL,yy);ctx.lineTo(w-padR,yy);ctx.stroke();ctx.fillStyle='#6f8693';ctx.fillText(fmt(max-(max-min)*i/4),w-padR+10,yy);}
for(let i=0;i<6;i++){const xx=padL+i*plotW/5;ctx.strokeStyle='#c5d6df08';ctx.beginPath();ctx.moveTo(xx,padT);ctx.lineTo(xx,h-padB);ctx.stroke();ctx.fillStyle='#647e8c';ctx.textAlign=i===0?'left':i===5?'right':'center';const total=9*60+i*60;ctx.fillText(String(Math.floor(total/60)).padStart(2,'0')+':'+String(total%60).padStart(2,'0'),xx,h-10);}ctx.textAlign='left';
samples.forEach((p,i)=>{ctx.fillStyle=prices[i]>=(prices[i-1]??prices[i])?'#7edab027':'#dc85972b';ctx.fillRect(x(i)-1.2,h-padB-p.volume*.44,Math.max(1.5,plotW/samples.length*.65),p.volume*.44);});
if(mode==='line'){const gradient=ctx.createLinearGradient(0,padT,0,h-50);gradient.addColorStop(0,stock().change>=0?'#79e9c22b':'#ef93a326');gradient.addColorStop(1,'#79e9c200');ctx.beginPath();prices.forEach((p,i)=>{if(!i)ctx.moveTo(x(i),y(p));else ctx.lineTo(x(i),y(p));});ctx.lineTo(x(prices.length-1),h-52);ctx.lineTo(x(0),h-52);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();ctx.beginPath();prices.forEach((p,i)=>{if(!i)ctx.moveTo(x(i),y(p));else ctx.lineTo(x(i),y(p));});ctx.strokeStyle=color;ctx.lineWidth=1.8;ctx.lineJoin='round';ctx.shadowColor=color;ctx.shadowBlur=7;ctx.stroke();ctx.shadowBlur=0;}else{prices.forEach((p,i)=>{const open=prices[i-1]??p;const high=Math.max(open,p)+spread*(.015+Math.abs(Math.sin(i))* .014),low=Math.min(open,p)-spread*.022;ctx.strokeStyle=ctx.fillStyle=p>=open?'#8fe9cf':'#ef93a3';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x(i),y(high));ctx.lineTo(x(i),y(low));ctx.stroke();ctx.fillRect(x(i)-plotW/samples.length*.3,Math.min(y(open),y(p)),Math.max(2,plotW/samples.length*.6),Math.max(1,Math.abs(y(open)-y(p))));});}
const last=prices.at(-1),yy=y(last);ctx.setLineDash([3,4]);ctx.strokeStyle=color+'50';ctx.beginPath();ctx.moveTo(padL,yy);ctx.lineTo(w-padR+5,yy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=color;ctx.fillRect(w-padR+4,yy-9,61,18);ctx.fillStyle='#10251f';ctx.font='bold 9px sans-serif';ctx.fillText(fmt(last),w-padR+9,yy);ctx.font='9px sans-serif';ctx.beginPath();ctx.arc(x(prices.length-1),yy,3,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();if(!reduced.matches){ctx.beginPath();ctx.arc(x(prices.length-1),yy,5+(Math.sin(time*.003)+1)*2,0,Math.PI*2);ctx.strokeStyle=color+'45';ctx.stroke();}
if(hover>=0){const index=Math.min(prices.length-1,hover),xx=x(index),hy=y(prices[index]);ctx.setLineDash([3,4]);ctx.strokeStyle='#bfdbdc66';ctx.beginPath();ctx.moveTo(xx,padT);ctx.lineTo(xx,h-padB);ctx.moveTo(padL,hy);ctx.lineTo(w-padR,hy);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(xx,hy,4,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();const tooltip=$('chartTooltip');tooltip.hidden=false;const minutes=9*60+Math.round(index/(samples.length-1)*300);tooltip.textContent=String(Math.floor(minutes/60)).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0')+' · '+fmt(prices[index])+' KRW';tooltip.style.left=Math.max(0,Math.min(w-170,xx+12))+'px';tooltip.style.top=Math.max(0,hy-48)+'px';}}
function loop(time){if(!document.hidden&&time-lastPaint>30){draw(time);lastPaint=time;}if(!reduced.matches)frame=requestAnimationFrame(loop);}
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();hover=Math.max(0,Math.min(samples.length-1,Math.round((e.clientX-r.left-10)/(w-75)*(samples.length-1))));draw(performance.now());});canvas.addEventListener('pointerleave',()=>{hover=-1;$('chartTooltip').hidden=true;draw(performance.now());});canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();hover=Math.max(0,Math.min(samples.length-1,(hover<0?45:hover)+(e.key==='ArrowRight'?1:-1)));draw(performance.now());}if(e.key==='Escape'){hover=-1;$('chartTooltip').hidden=true;draw(performance.now());}});canvas.addEventListener('blur',()=>{hover=-1;$('chartTooltip').hidden=true;});
function setMode(value){mode=value;for(const type of ['line','candle']){$(type+'Mode').classList.toggle('selected',type===mode);$(type+'Mode').setAttribute('aria-pressed',String(type===mode));}draw(performance.now());}$('lineMode').onclick=()=>setMode('line');$('candleMode').onclick=()=>setMode('candle');new ResizeObserver(resize).observe(canvas);reduced.addEventListener('change',()=>{cancelAnimationFrame(frame);draw(performance.now());if(!reduced.matches)frame=requestAnimationFrame(loop);});
function addAsset(el,asset='parrot-yellow',className='asset-3d'){if(!el||el.querySelector(':scope > img.asset-3d'))return;const img=document.createElement('img');img.src=`assets/${asset}.png`;img.alt='';img.className=className;img.width=28;img.height=28;img.draggable=false;el.prepend(img);}
function decorateAssets(){
 const logo=document.querySelector('.wordmark');if(!logo.querySelector('.brand-copy')){logo.innerHTML='<img class="brand-coin" src="assets/parrot-yellow.png" alt="앵무새가 새겨진 3D 껄무새 코인" width="52" height="52"><div class="brand-copy">껄무새 투자거래소<span>KKEOLMUSAE EXCHANGE</span></div>';}
 document.querySelectorAll('nav a').forEach((el,i)=>addAsset(el,['glass-market','parrot-yellow','glass-portfolio'][i]));
 const sculpture=document.querySelector('.glass-sculpture');if(sculpture&&!sculpture.querySelector('img'))sculpture.innerHTML='<img class="red-coin" src="assets/parrot-red.png" alt="빨간 앵무새 껄무새 코인" width="130" height="130"><img class="yellow-coin" src="assets/parrot-yellow.png" alt="노란 앵무새 껄무새 코인" width="150" height="150">';
 addAsset($('profileButton'));addAsset($('nextDay'),'glass-market');addAsset(document.querySelector('.return-card .label'),'glass-market');
 addAsset(document.querySelector('.stock-title'),'parrot-yellow','asset-3d stock-asset');addAsset(document.querySelector('.order-stock'));addAsset($('submitOrder'));addAsset($('favorite'));addAsset($('help'),'glass-market');addAsset($('buyTab'),'glass-market');addAsset($('sellTab'),'glass-portfolio');addAsset($('resetPortfolio'),'glass-portfolio');addAsset($('allStocks'),'glass-market');addAsset($('tipMore'),'glass-market');addAsset($('browse'),'glass-market');addAsset($('closeToast'),'glass-portfolio');addAsset(document.querySelector('.practice'));
 document.querySelectorAll('.watch-row').forEach((el,i)=>{addAsset(el,['parrot-yellow','glass-market','parrot-red','glass-portfolio','parrot-red','glass-market'][i]);});
 document.querySelectorAll('td button').forEach(el=>addAsset(el));
 const empty=document.querySelector('.empty-holdings');if(empty)addAsset(empty,'glass-portfolio','asset-3d empty-asset');
 addAsset(document.querySelector('.tip'),'glass-market');
}
function renderOutcomeCoin(){
 const m=metrics(state),card=document.querySelector('.return-card');let coin=card.querySelector('.outcome-coin');if(!coin){coin=document.createElement('img');coin.className='outcome-coin';coin.width=90;coin.height=90;card.append(coin);}coin.hidden=m.returns===0;coin.src=`assets/parrot-${m.returns<0?'red':'yellow'}.png`;coin.alt=m.returns<0?'손실 상태의 빨간 앵무새 코인':'수익 상태의 노란 앵무새 코인';card.classList.toggle('has-outcome',m.returns!==0);
}
function showDayResult(){
 const m=metrics(state),positive=m.returns>0,negative=m.returns<0;
 $('resultCoin').hidden=!positive&&!negative;$('resultCoin').src=`assets/parrot-${negative?'red':'yellow'}.png`;$('resultCoin').alt=negative?'빨간 앵무새 코인':'노란 앵무새 코인';
 $('resultTitle').textContent=positive?'좋은 선택이었어요!':negative?'아쉬운 하루였어요.':'새로운 하루가 시작됐어요.';
 $('resultDescription').textContent=positive?'투자한 종목의 총 수익률이 플러스예요.':negative?'투자한 종목의 총 수익률이 마이너스예요.':m.invested?'총 수익률에 변동이 없어요.':'아직 투자한 종목이 없어요. 첫 투자를 시작해 보세요.';
 $('resultRate').textContent=pct(m.returns);$('resultRate').className=positive?'positive':negative?'negative':'';
 $('resultBalance').textContent=fmt(state.appliedCoins)+' 코인';$('resultDialog').classList.toggle('loss-result',negative);$('resultDialog').showModal();playSound(positive?'buy':negative?'error':'tap');
}
$('closeResult').onclick=()=>{$('resultDialog').close();$('nextDay').focus();};
const assetObserver=new MutationObserver(()=>decorateAssets());for(const id of ['watchlist','holdings','profileButton','submitOrder'])assetObserver.observe($(id),{childList:true});
render();decorateAssets();rebuildChart();resize();if(!reduced.matches)frame=requestAnimationFrame(loop);


