// Decorative only: the portfolio result is calculated by the trading engine.
export function createOutcomeEffects(dialog){
 const canvas=document.createElement('canvas');canvas.className='outcome-effects';canvas.setAttribute('aria-hidden','true');canvas.setAttribute('popover','manual');dialog.append(canvas);
 const ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)');let frame=0,particles=[],started=0,last=0,width=0,height=0,kind=0,burst=0;
 function stop(){cancelAnimationFrame(frame);frame=0;particles=[];if(canvas.matches(':popover-open'))canvas.hidePopover();canvas.hidden=true;ctx?.clearRect(0,0,width,height)}
 function resize(){width=innerWidth;height=innerHeight;const scale=Math.min(devicePixelRatio||1,2);canvas.width=width*scale;canvas.height=height*scale;ctx?.setTransform(scale,0,0,scale,0,0)}
 function fireworks(){const x=width*(.15+Math.random()*.7),y=height*(.12+Math.random()*.32),count=width<600?46:72;for(let i=0;i<count;i++){const a=Math.PI*2*i/count,speed=70+Math.random()*180;particles.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:1.2+Math.random()*.7,age:0,hue:[42,155,190,325][burst%4],size:1.4+Math.random()*1.8})}}
 function money(){const count=width<600?32:52;for(let i=0;i<count;i++)particles.push({x:Math.random()*width,y:-60-Math.random()*height*.65,vx:(Math.random()-.5)*90,vy:70+Math.random()*180,angle:Math.random()*6.28,spin:(Math.random()-.5)*4,size:width<600?26+Math.random()*12:32+Math.random()*17,delay:Math.random()*.8,bounces:0})}
 function paint(now){if(!dialog.open||document.hidden||reduced.matches){stop();return}const elapsed=(now-started)/1000,dt=Math.min((now-last)/1000,.04);last=now;ctx.clearRect(0,0,width,height);ctx.globalAlpha=Math.min(1,Math.max(0,(4.5-elapsed)/.8));
  if(kind>0){while(burst<5&&elapsed>=burst*.48){fireworks();burst++}particles=particles.filter(p=>p.age<p.life);for(const p of particles){p.age+=dt;p.vy+=100*dt;const oldX=p.x,oldY=p.y;p.x+=p.vx*dt;p.y+=p.vy*dt;ctx.save();ctx.globalAlpha*=Math.max(0,1-p.age/p.life);ctx.strokeStyle=`hsl(${p.hue} 95% 70%)`;ctx.lineWidth=p.size;ctx.lineCap='round';ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=9;ctx.beginPath();ctx.moveTo(oldX-p.vx*.025,oldY-p.vy*.025);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.restore()}}
  else for(const p of particles){if(elapsed<p.delay)continue;const floor=height-12-p.size*.25;if(p.bounces<3){p.vy+=510*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.angle+=p.spin*dt;if(p.y>=floor){p.y=floor;p.vy=-Math.abs(p.vy)*.26;p.vx*=.55;p.spin*=.35;p.bounces++}}ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.scale(1,.7+.3*Math.cos(elapsed*5+p.delay));const w=p.size,h=p.size*.5;ctx.shadowColor='#0006';ctx.shadowBlur=5;ctx.fillStyle='#9bbd94';ctx.fillRect(-w/2,-h/2,w,h);ctx.shadowBlur=0;ctx.strokeStyle='#426b50';ctx.lineWidth=1;ctx.strokeRect(-w/2+3,-h/2+3,w-6,h-6);ctx.fillStyle='#577f60';ctx.beginPath();ctx.ellipse(0,0,w*.13,h*.3,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d4e4b5';ctx.font=`600 ${Math.round(h*.5)}px Pretendard,sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('₩',0,1);ctx.restore()}
  if(elapsed<4.5)frame=requestAnimationFrame(paint);else stop();
 }
 function play(result){stop();if(!result||!ctx||reduced.matches||!dialog.open)return;kind=Math.sign(result);resize();canvas.hidden=false;if(typeof canvas.showPopover==='function')canvas.showPopover();burst=0;if(kind<0)money();started=last=performance.now();frame=requestAnimationFrame(paint)}
 dialog.addEventListener('close',stop);dialog.addEventListener('cancel',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});reduced.addEventListener('change',()=>{if(reduced.matches)stop()});window.addEventListener('resize',()=>{if(frame)resize()});stop();return{play,stop};
}
