import{mountSimulation}from './simulation.js';
import{flashChange,forgetFlash}from './live-motion.js';
import{mountStocks}from './stocks.js';
import{FEE,freshAccount,availableCash,availableQty,validateAccount,placeOrder,settlePending,cancelOrder}from './account.js';
const $=id=>document.getElementById(id),money=n=>Number.isFinite(n)?n.toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:n<1?5:2}):'—',num=n=>Number.isFinite(n)?n.toLocaleString('en-US',{maximumFractionDigits:8}):'—',percent=n=>Number.isFinite(n)?(n>=0?'+':'')+n.toFixed(2)+'%':'—';
const COINS=[['BTC','비트코인'],['ETH','이더리움'],['SOL','솔라나'],['XRP','엑스알피'],['DOGE','도지코인'],['ADA','에이다'],['LINK','체인링크'],['AVAX','아발란체']].map(([symbol,name])=>({symbol,name,id:symbol+'-USD',image:'assets/'+symbol.toLowerCase()+'.png'}));
const API='https://api.exchange.coinbase.com',KEY='nova-paper-v1',quotes={},books={};let selected=COINS[0],period=3600,candles=[],chartType='candle',side='buy',view='trade',favoriteOnly=false,account=freshAccount(),favorites=[],socket,retryTimer,socketGeneration=0,marketRequest=0,chartRequest=0,lastTick=0,hover=null,toastTimer,pollBusy=false;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(validateAccount(saved)&&Object.keys(saved.positions).every(id=>COINS.some(c=>c.id===id))&&saved.pending.every(o=>COINS.some(c=>c.id===o.id)))account=saved;const savedStars=JSON.parse(localStorage.getItem(KEY+'-stars'));if(Array.isArray(savedStars))favorites=savedStars.filter(s=>COINS.some(c=>c.id===s))}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(account))}catch{toast('브라우저 저장 공간에 기록하지 못했습니다.')}}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4000)}
async function get(path){const r=await fetch(API+path,{signal:AbortSignal.timeout(10000),cache:'no-store'});if(!r.ok)throw Error('시세 서버 응답 '+r.status);return r.json()}
function pct(q){return q?.open>0?(q.price/q.open-1)*100:NaN}function fresh(q){return q&&Date.now()-q.at<60000}function coin(id){return COINS.find(c=>c.id===id)}
const visibleNumber=n=>Number.isFinite(n)?Number(money(n).replace(/[^0-9.-]/g,'')):NaN;
function renderMarket(){
 const term=$('search').value.trim().toLowerCase(),list=COINS.filter(c=>(c.symbol.toLowerCase().includes(term)||c.name.includes(term))&&(!favoriteOnly||favorites.includes(c.id)));
 $('coin-list').innerHTML=list.map(c=>{const q=quotes[c.id],change=pct(q);return`<button class="coin-row ${selected.id===c.id?'selected':''}" data-coin="${c.id}" aria-pressed="${selected.id===c.id}"><img src="${c.image}" alt=""><span><strong>${c.name}</strong><small>${c.symbol}</small></span><span class="coin-values"><b>${money(q?.price)}</b><em class="${change>=0?'up':'down'}">${percent(change)}</em></span></button>`}).join('');$('market-empty').hidden=!!list.length;
 $('ticker').innerHTML=COINS.map(c=>`<button data-coin="${c.id}"><img src="${c.image}" alt="">${c.symbol}<b>${money(quotes[c.id]?.price)}</b><em class="${pct(quotes[c.id])>=0?'up':'down'}">${percent(pct(quotes[c.id]))}</em></button>`).join('');
 const sorting=$('sort-market').value,ranked=[...COINS].sort((a,b)=>sorting==='up'?(pct(quotes[b.id])||0)-(pct(quotes[a.id])||0):sorting==='down'?(pct(quotes[a.id])||0)-(pct(quotes[b.id])||0):(quotes[b.id]?.volume*quotes[b.id]?.price||0)-(quotes[a.id]?.volume*quotes[a.id]?.price||0));
 $('market-table').innerHTML=ranked.map(c=>{const q=quotes[c.id];return`<tr data-market-coin="${c.id}"><td><img src="${c.image}" alt="">${c.name}<small>${c.symbol}</small></td><td>${money(q?.price)}</td><td class="${pct(q)>=0?'up':'down'}">${percent(pct(q))}</td><td>${num(q?.volume)}</td><td>${money(q?.volume*q?.price)}</td><td><button data-coin="${c.id}">거래</button></td></tr>`}).join('');
 flashMarkets();
}
function flashMarkets(){for(const c of COINS){const values=[visibleNumber(quotes[c.id]?.price),Number(pct(quotes[c.id]).toFixed(2))];for(const [key,selector]of[['list','#coin-list [data-coin]'],['ticker','#ticker [data-coin]'],['market','#market-table [data-market-coin]']]){const el=[...document.querySelectorAll(selector)].find(el=>(el.dataset.coin||el.dataset.marketCoin)===c.id);if(el)flashChange(key+c.id,values,el)}}}
function renderQuote(){const q=quotes[selected.id],b=books[selected.id];for(const selector of ['.asset-heading','.order-panel','.depth-panel'])flashChange(selector+selected.id,[visibleNumber(q?.price)],document.querySelector(selector));$('selected-name').textContent=selected.name;$('selected-symbol').textContent=selected.symbol+' / USD';$('selected-icon').src=selected.image;$('selected-icon').alt=selected.name;$('qty-symbol').textContent=selected.symbol;$('price').textContent=money(q?.price);$('change').textContent=percent(pct(q))+' · 24H';$('change').className=pct(q)>=0?'up':'down';$('high').textContent=money(q?.high);$('low').textContent=money(q?.low);$('volume').textContent=num(q?.volume)+' '+selected.symbol;$('spread').textContent=b?money(b.ask-b.bid):'—';$('favorite').textContent=favorites.includes(selected.id)?'관심 해제':'관심 추가';$('mid-price').textContent=money(q?.price);$('updated').textContent=q?'수신 '+new Date(q.at).toLocaleTimeString('ko-KR')+' · Coinbase':'Coinbase · USD 마켓';renderEstimate()}
function renderEstimate(){const q=books[selected.id],type=$('order-type').value,price=type==='limit'?Number($('limit-price').value):side==='buy'?q?.ask:q?.bid,qty=Number($('quantity').value),total=Number.isFinite(price)&&qty>0?price*qty:0;$('order-total').textContent=money(total);$('order-fee').textContent=money(total*FEE);$('buying-power').textContent=side==='buy'?money(availableCash(account)):num(availableQty(account,selected.id))+' '+selected.symbol;const ready=q&&Date.now()-q.at<=15000;$('submit-order').disabled=!ready;$('submit-order').textContent=ready?selected.symbol+' 가상 '+(side==='buy'?'매수':'매도'):'최신 호가 대기';$('submit-order').style.background=side==='buy'?'':'#eda2a8';$('limit-label').hidden=type!=='limit';$('limit-price').required=type==='limit'}
function renderAccount(){let value=account.cash,stale=false;const rows=[];for(const[id,p]of Object.entries(account.positions)){const c=coin(id),q=quotes[id];if(!c)continue;const v=q?p.qty*q.price:p.cost;value+=v;if(!fresh(q))stale=true;rows.push({c,p,q,v})}const net=account.deposited-account.withdrawn,profit=value-net;$('equity').textContent=money(value)+(stale?' *':'');$('cash').textContent=money(availableCash(account));flashChange('equity',[visibleNumber(value)],$('equity').parentElement);flashChange('cash',[visibleNumber(availableCash(account))],$('cash').parentElement);flashChange('pnl',[visibleNumber(profit)],$('pnl').parentElement);$('reserved').textContent='예약 주문 '+money(account.cash-availableCash(account));$('pnl').textContent=(profit>=0?'+':'')+money(profit);$('pnl').className=profit>=0?'up':'down';$('holdings').innerHTML=rows.length?rows.map(({c,p,q,v})=>`<tr><td><img src="${c.image}" alt="">${c.name}</td><td>${num(p.qty)} ${c.symbol}</td><td>${money(p.cost/p.qty)}</td><td>${money(v)}${fresh(q)?'':' *'}</td><td class="${v-p.cost>=0?'up':'down'}">${money(v-p.cost)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">보유 중인 코인이 없습니다. 거래소에서 첫 가상 거래를 시작해 보세요.</td></tr>';
 $('allocation').innerHTML=[{name:'USD',value:account.cash},...rows.map(r=>({name:r.c.symbol,value:r.v}))].map(r=>`<div class="allocation-row"><span>${r.name}</span><div class="allocation-track"><span style="width:${value>0?r.value/value*100:0}%"></span></div><span>${(value>0?r.value/value*100:0).toFixed(1)}%</span></div>`).join('');
 $('account-info').innerHTML=[['계좌 종류','가상 투자 계좌'],['총 가상 입금',money(account.deposited)],['총 가상 출금',money(account.withdrawn)],['실현·미실현 합산 손익',money(profit)],['미체결 주문',account.pending.length+'건'],['시세 상태',stale?'일부 자산에 최근 수신가 또는 매입원가 적용':'최근 수신 시세 기준']].map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('');
 $('pending').innerHTML=account.pending.length?account.pending.map(o=>`<tr><td>${o.id}</td><td class="${o.side==='buy'?'up':'down'}">${o.side==='buy'?'매수':'매도'}</td><td>${num(o.qty)}</td><td>${money(o.limit)}</td><td>${new Date(o.time).toLocaleString('ko-KR')}</td><td><button data-cancel="${o.key}">취소</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">미체결 주문이 없습니다.</td></tr>';
 $('history').innerHTML=account.history.length?account.history.map(o=>`<tr><td>${o.id}</td><td>${o.side==='buy'?'매수':'매도'}</td><td>${o.status}</td><td>${num(o.qty)}</td><td>${money(o.price)}</td><td>${money(o.fee)}</td><td>${new Date(o.time).toLocaleString('ko-KR')}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">아직 주문 내역이 없습니다.</td></tr>';
 $('funding-history').innerHTML=account.funding.length?account.funding.map(f=>`<div class="funding-row"><span>가상 ${f.type==='deposit'?'입금':'출금'}</span><b>${money(f.amount)}</b><time>${new Date(f.time).toLocaleString('ko-KR')}</time></div>`).join(''):'<p class="empty">추가 가상 입출금 내역이 없습니다.</p>';renderEstimate()}
function acceptBook(id,bid,ask,at){if(!(bid>0&&ask>=bid))return;books[id]={bid,ask,at};const next=settlePending(account,id,books[id]);if(next!==account){account=next;save();toast('지정가 가상 주문이 체결되었습니다.');renderAccount()}}
async function refreshStats(){for(let i=0;i<COINS.length;i+=2){await Promise.allSettled(COINS.slice(i,i+2).map(async c=>{try{const s=await get('/products/'+c.id+'/stats'),old=quotes[c.id];quotes[c.id]={price:old?.price??Number(s.last),open:Number(s.open),high:Number(s.high),low:Number(s.low),volume:Number(s.volume),at:old?.at??Date.now()}}catch{}}));renderMarket();renderQuote();await new Promise(r=>setTimeout(r,250))}renderAccount()}
async function refreshDetail(){if(pollBusy||document.hidden)return;pollBusy=true;const id=selected.id,request=marketRequest;try{const result=await Promise.allSettled([get('/products/'+id+'/book?level=2'),get('/products/'+id+'/trades?limit=12'),get('/products/'+id+'/ticker')]);if(request!==marketRequest)return;const[book,trades,ticker]=result;
 if(book.status==='fulfilled'&&book.value.bids?.length&&book.value.asks?.length){const b=book.value;acceptBook(id,Number(b.bids[0][0]),Number(b.asks[0][0]),Date.now());renderBook(b);$('book-status').textContent='수신 '+new Date().toLocaleTimeString('ko-KR')}else $('book-status').textContent='호가 연결 지연';
 if(trades.status==='fulfilled'&&Array.isArray(trades.value))renderTrades(trades.value);
 if(ticker.status==='fulfilled'){const t=ticker.value,old=quotes[id]||{};quotes[id]={...old,price:Number(t.price),at:Date.now()};if(t.bid&&t.ask)acceptBook(id,Number(t.bid),Number(t.ask),Date.now());}
 renderQuote();renderMarket();renderAccount();
 }finally{pollBusy=false}}
function renderBook(book){for(const[side,items]of[['asks',book.asks],['bids',book.bids]]){const first=items.slice(0,5),max=Math.max(...first.map(r=>Number(r[1])));let cumulative=0;const rows=first.map(row=>{const quantity=Number(row[1]);cumulative+=quantity;return`<div class="book-row ${side==='asks'?'ask':''}"><div class="depth-bar" style="width:${quantity/max*100}%"></div><span class="${side==='asks'?'down':'up'}">${money(Number(row[0]))}</span><span>${num(quantity)}</span><span>${num(cumulative)}</span></div>`});$(side).innerHTML=(side==='asks'?rows.reverse():rows).join('');[...$(side).children].forEach((el,i)=>{const row=(side==='asks'?[...first].reverse():first)[i];flashChange(selected.id+side+i,[Number(row[0]),Number(row[1])],el)})}}
function renderTrades(trades){if(trades.length)flashChange('trades-'+selected.id,[Number(trades[0].price),Number(trades[0].size)],document.querySelector('.fills-panel')); $('market-trades').innerHTML=trades.slice(0,10).map(t=>`<div class="trade-row"><span class="${t.side==='sell'?'up':'down'}">${money(Number(t.price))}</span><span>${num(Number(t.size))}</span><span>${new Date(t.time).toLocaleTimeString('ko-KR',{hour12:false})}</span></div>`).join('')}
async function loadCandles(){const id=selected.id,p=period,request=++chartRequest;candles=[];$('chart-state').hidden=false;$('chart-state').textContent='실제 캔들을 불러오는 중';draw();try{const rows=await get('/products/'+id+'/candles?granularity='+p);if(request!==chartRequest)return;if(!Array.isArray(rows)||!rows.length)throw Error('empty');candles=rows.map(r=>({time:r[0],low:r[1],high:r[2],open:r[3],close:r[4],volume:r[5]})).sort((a,b)=>a.time-b.time).slice(-100);$('chart-state').hidden=true;draw()}catch{if(request!==chartRequest)return;$('chart-state').textContent='차트를 불러오지 못했습니다. 새로고침을 눌러주세요.';$('ohlc').textContent='데이터 연결 대기';$('candle-time').textContent='—'}}
function connect(){clearTimeout(retryTimer);const generation=++socketGeneration;if(socket)socket.close();$('connection').textContent='시세 연결 중';socket=new WebSocket('wss://ws-feed.exchange.coinbase.com');socket.onopen=()=>socket.send(JSON.stringify({type:'subscribe',product_ids:COINS.map(c=>c.id),channels:['ticker','heartbeat']}));socket.onmessage=e=>{if(generation!==socketGeneration)return;let t;try{t=JSON.parse(e.data)}catch{return}if(t.type!=='ticker'||!coin(t.product_id))return;const id=t.product_id,price=Number(t.price);if(!(price>0))return;lastTick=Date.now();quotes[id]={price,open:Number(t.open_24h),high:Number(t.high_24h),low:Number(t.low_24h),volume:Number(t.volume_24h),at:Date.now()};const sourceTime=Date.parse(t.time);if(Number.isFinite(sourceTime)&&Math.abs(Date.now()-sourceTime)<60000)acceptBook(id,Number(t.best_bid),Number(t.best_ask),Date.now());if(id===selected.id&&candles.length&&Number.isFinite(sourceTime)){const stamp=Math.floor(sourceTime/1000/period)*period,last=candles.at(-1);if(stamp===last.time){last.close=price;last.high=Math.max(last.high,price);last.low=Math.min(last.low,price);last.volume+=Number(t.last_size)||0}else if(stamp>last.time){candles.push({time:stamp,open:price,close:price,high:price,low:price,volume:Number(t.last_size)||0});if(candles.length>100)candles.shift()}draw()}};socket.onclose=()=>{if(generation===socketGeneration)retryTimer=setTimeout(connect,10000)};socket.onerror=()=>{$('connection').textContent='REST 시세로 연결 중'}}
function status(){const q=quotes[selected.id],live=Date.now()-lastTick<15000;$('connection').textContent=live?'코인 LIVE · 실시간 연결':fresh(q)?'코인 POLL · 5초 간격 조회':'코인 시세 지연 · 재연결 대기';renderQuote();renderMarket();renderAccount()}
async function selectCoin(id){const c=coin(id);if(!c)return;selected=c;for(const selector of ['.asset-heading','.order-panel','.depth-panel'])forgetFlash(selector+selected.id);marketRequest++;hover=null;$('quantity').value='';$('limit-price').value='';$('order-error').textContent='';$('asks').innerHTML=$('bids').innerHTML='';$('market-trades').innerHTML='<p class="empty">체결 데이터 연결 중</p>';showView('trade');renderMarket();renderQuote();loadCandles();refreshDetail()}
const titles={'sim-crypto':['AI 가상투자 시뮬레이션','코인의 과거 가격으로 여러 투자 시나리오를 탐색하세요.'],'sim-korea':['AI 가상투자 시뮬레이션','국내 주식의 과거 가격으로 가상 투자 결과를 비교하세요.'],trade:['시장을 읽는 새로운 시선.','실제 시세를 따라, 가상 자금으로 나만의 투자 전략을 경험하세요.'],markets:['움직이는 시장, 한눈에.','주요 코인의 가격과 거래 흐름을 비교하세요.'],korea:['한국 시장을 더 가까이.','국내 주요 기업의 차트와 가격 흐름을 살펴보세요.'],wallet:['나의 투자, 나의 포트폴리오.','가상 자산의 구성과 손익을 한곳에서 관리하세요.'],orders:['모든 선택을 기록하다.','접수한 주문부터 체결 내역까지 투명하게 확인하세요.']};
function showView(name){if(!titles[name])return;view=name;if(name.startsWith('sim-')&&!$('view-'+name).children.length)mountSimulation($('view-'+name),name==='sim-korea'?'korea':'crypto');document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!=='view-'+name);document.querySelectorAll('nav [data-view]').forEach(b=>{b.classList.toggle('active',(b.dataset.view===name||b.dataset.view==='sim-crypto'&&name==='sim-korea'));b.setAttribute('aria-current',b.dataset.view===name?'page':'false')});$('page-title').textContent=titles[name][0];$('page-description').textContent=titles[name][1];history.replaceState(null,'','#'+name);if(name==='korea'&&!$('korea-chart').children.length)loadKorea();if(name==='trade')resize()}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)showView(nav.dataset.view);const c=e.target.closest('[data-coin]');if(c)selectCoin(c.dataset.coin);const cancel=e.target.closest('[data-cancel]');if(cancel){account=cancelOrder(account,cancel.dataset.cancel);save();renderAccount();toast('주문이 취소되었습니다.')}});
$('search').oninput=renderMarket;$('sort-market').onchange=renderMarket;$('all-filter').onclick=()=>{favoriteOnly=false;$('all-filter').classList.add('active');$('star-filter').classList.remove('active');renderMarket()};$('star-filter').onclick=()=>{favoriteOnly=true;$('star-filter').classList.add('active');$('all-filter').classList.remove('active');renderMarket()};$('favorite').onclick=()=>{favorites=favorites.includes(selected.id)?favorites.filter(x=>x!==selected.id):[...favorites,selected.id];try{localStorage.setItem(KEY+'-stars',JSON.stringify(favorites))}catch{toast('관심종목을 저장하지 못했습니다.')}renderQuote();renderMarket()};
document.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{side=b.dataset.side;document.querySelectorAll('[data-side]').forEach(x=>x.classList.toggle('active',x===b));$('order-error').textContent='';renderEstimate()});$('order-type').onchange=renderEstimate;$('quantity').oninput=renderEstimate;$('limit-price').oninput=renderEstimate;document.querySelectorAll('[data-percent]').forEach(b=>b.onclick=()=>{const q=books[selected.id],price=$('order-type').value==='limit'?Number($('limit-price').value):q?.ask,max=side==='buy'?availableCash(account)/(price*(1+FEE)):availableQty(account,selected.id);if(!Number.isFinite(max)||max<=0)return toast('가격과 주문 가능 잔액을 확인해 주세요.');$('quantity').value=Math.floor(max*Number(b.dataset.percent)/100*1e8)/1e8;renderEstimate()});
$('order-form').onsubmit=e=>{e.preventDefault();try{const pending=account.pending.length;account=placeOrder(account,{id:selected.id,side,qty:Number($('quantity').value),type:$('order-type').value,limit:Number($('limit-price').value)},books[selected.id]);save();renderAccount();$('order-error').textContent='';toast(account.pending.length>pending?'가상 지정가 주문이 접수되었습니다.':'가상 주문이 체결되었습니다.')}catch(error){$('order-error').textContent=error.message}};
$('periods').onclick=e=>{if(!e.target.dataset.period)return;period=Number(e.target.dataset.period);$('periods').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===e.target));loadCandles()};$('chart-mode').onclick=()=>{chartType=chartType==='candle'?'line':'candle';$('chart-mode').textContent=chartType==='candle'?'라인 보기':'캔들 보기';draw()};$('chart-refresh').onclick=loadCandles;$('reconnect').onclick=()=>{connect();refreshStats();refreshDetail();loadCandles()};
const canvas=$('chart'),ctx=canvas.getContext('2d');let width=0,height=0;function resize(){width=canvas.clientWidth;height=canvas.clientHeight;if(!width||!height)return;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw()}new ResizeObserver(resize).observe(canvas);
function draw(){if(!width||!height)return;ctx.clearRect(0,0,width,height);if(!candles.length)return;const bars=candles,left=8,right=width-73,top=10,bottom=height-70,low=Math.min(...bars.map(b=>b.low)),high=Math.max(...bars.map(b=>b.high)),pad=Math.max((high-low)*.15,high*.001),min=low-pad,max=high+pad,step=(right-left)/bars.length,x=i=>left+(i+.5)*step,y=p=>top+(max-p)/(max-min)*(bottom-top);ctx.font='10px Pretendard';ctx.lineWidth=1;for(let i=0;i<5;i++){const yy=top+i*(bottom-top)/4;line(left,yy,right,yy,'#253124');ctx.fillStyle='#7e9073';ctx.fillText(money(max-(max-min)*i/4),right+7,yy+4)}for(let i=0;i<6;i++){const xx=left+i*(right-left)/5;line(xx,top,xx,height-24,'#1d291d');const b=bars[Math.min(bars.length-1,Math.floor(i*(bars.length-1)/5))],d=new Date(b.time*1000);ctx.fillStyle='#75866b';ctx.textAlign=i===5?'right':'left';ctx.fillText(period>=3600?d.toLocaleDateString('ko-KR',{month:'2-digit',day:'2-digit'}):d.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false}),xx,height-7)}ctx.textAlign='left';const maxVolume=Math.max(1,...bars.map(b=>b.volume));bars.forEach((b,i)=>{const col=b.close>=b.open?'#80cf9a':'#e17e86',xx=x(i);ctx.fillStyle=col;if(chartType==='candle'){line(xx,y(b.high),xx,y(b.low),col);ctx.fillRect(xx-step*.3,y(Math.max(b.open,b.close)),Math.max(1,step*.6),Math.max(1,Math.abs(y(b.open)-y(b.close))))}ctx.globalAlpha=.4;const v=b.volume/maxVolume*35;ctx.fillRect(xx-step*.3,height-26-v,Math.max(1,step*.6),v);ctx.globalAlpha=1});if(chartType==='line'){ctx.beginPath();bars.forEach((b,i)=>i?ctx.lineTo(x(i),y(b.close)):ctx.moveTo(x(i),y(b.close)));ctx.strokeStyle='#bde681';ctx.lineWidth=1.7;ctx.stroke()}ctx.beginPath();bars.forEach((_,i)=>{const sample=bars.slice(Math.max(0,i-19),i+1),avg=sample.reduce((n,b)=>n+b.close,0)/sample.length;i?ctx.lineTo(x(i),y(avg)):ctx.moveTo(x(i),y(avg))});ctx.strokeStyle='#c9aa69';ctx.lineWidth=1;ctx.stroke();const last=bars.at(-1),yy=y(last.close);ctx.setLineDash([3,4]);line(left,yy,right,yy,'#94bd6877');ctx.setLineDash([]);ctx.fillStyle='#bce77c';ctx.fillRect(right+3,yy-9,69,20);ctx.fillStyle='#1c2b12';ctx.fillText(money(last.close),right+7,yy+4);$('ohlc').textContent='O '+num(last.open)+'  H '+num(last.high)+'  L '+num(last.low)+'  C '+num(last.close);$('candle-time').textContent=new Date(last.time*1000).toLocaleString('ko-KR');
 if(hover&&hover.x<right){const i=Math.min(bars.length-1,Math.max(0,Math.floor((hover.x-left)/step))),b=bars[i];ctx.setLineDash([3,3]);line(x(i),top,x(i),height-25,'#829273');ctx.setLineDash([]);$('chart-tooltip').hidden=false;$('chart-tooltip').textContent=new Date(b.time*1000).toLocaleString('ko-KR')+' · '+money(b.close);$('chart-tooltip').style.left=Math.max(4,Math.min(width-240,hover.x+8))+'px';$('chart-tooltip').style.top=Math.max(8,hover.y-40)+'px'}else $('chart-tooltip').hidden=true;
}function line(a,b,c,d,color){ctx.beginPath();ctx.strokeStyle=color;ctx.moveTo(a,b);ctx.lineTo(c,d);ctx.stroke()}canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect();hover={x:e.clientX-r.left,y:e.clientY-r.top};draw()};canvas.onpointerleave=()=>{hover=null;draw()};
function loadKorea(){mountStocks($('korea-chart'),$('korea-symbol'))}
function modal(title,content){$('dialog-title').textContent=title;$('dialog-content').innerHTML=content;$('dialog').showModal()}$('close-dialog').onclick=()=>$('dialog').close();
function funding(type){modal(type==='deposit'?'가상 자금 충전':'가상 자금 출금',`<p>실제 돈이 이동하지 않는 모의 ${type==='deposit'?'입금':'출금'}입니다.</p><form id="funding-form"><label>금액 (USD)<input id="funding-amount" type="number" min="1" max="1000000" step="0.01" value="10000" required></label><button class="primary">가상 ${type==='deposit'?'입금':'출금'} 확인</button><p id="funding-error" role="alert"></p></form>`);$('funding-form').onsubmit=e=>{e.preventDefault();const amount=Number($('funding-amount').value);if(!Number.isFinite(amount)||amount<1||amount>1000000)return;if(type==='withdraw'&&amount>availableCash(account)){$('funding-error').textContent='주문에 예약되지 않은 현금 범위에서 출금할 수 있습니다.';return}account.cash+=type==='deposit'?amount:-amount;account[type==='deposit'?'deposited':'withdrawn']+=amount;account.funding.unshift({type,amount,time:new Date().toISOString()});save();renderAccount();$('dialog').close();toast('가상 자금 '+(type==='deposit'?'충전':'출금')+' 완료')}}$('deposit').onclick=$('wallet-deposit').onclick=()=>funding('deposit');$('withdraw').onclick=()=>funding('withdraw');$('reset').onclick=()=>{modal('가상 계좌 초기화','<p>보유 자산과 주문 기록을 지우고 가상 자금 $100,000으로 다시 시작합니다.</p><button id="confirm-reset" class="primary">초기화 확인</button>');$('confirm-reset').onclick=()=>{account=freshAccount();save();renderAccount();$('dialog').close();toast('가상 계좌가 초기화되었습니다.')}};
const guide=()=>modal('NOVA 거래 가이드','<h3>1. 실제 시장을 살펴보세요</h3><p>코인 가격·캔들·호가·최근 체결은 Coinbase 공개 데이터입니다. 국내 주식은 Yahoo Finance 차트에서 확인하세요. 연결이 지연되면 수신 시각과 상태를 확인해 주세요.</p><h3>2. 가상 자금으로 주문하세요</h3><p>시장가 주문은 최신 최우선 호가로 즉시 가상 체결됩니다. 지정가 주문은 가격 조건이 맞을 때 체결되며 미체결 주문은 현금 또는 코인 수량을 예약합니다. 매수·매도 각각 0.10%의 가상 수수료가 적용됩니다.</p><h3>3. 기록을 확인하세요</h3><p>자산 화면에서 평가손익을, 주문 내역에서 체결·취소를 확인할 수 있습니다. 실제 시장의 유동성, 슬리피지, 주문 대기열은 재현하지 않습니다. 지정가 감시는 이 페이지가 열려 있고 시세가 연결되어 있을 때만 작동합니다.</p>');$('guide').onclick=$('learn').onclick=$('support').onclick=guide;$('privacy').onclick=()=>modal('저장 및 개인정보','<p>계좌와 관심종목은 현재 브라우저의 로컬 저장소에 보관됩니다. 로그인 없이 이용할 수 있습니다. 실제 지갑 연결은 사용하지 않습니다. 브라우저 데이터를 삭제하면 기록이 사라집니다. 여러 기기나 탭 사이의 계좌 동기화는 지원하지 않습니다.</p><p>시세와 국내 주식 차트를 표시하기 위해 Coinbase 및 Yahoo Finance에 접속합니다.</p>');$('sources').onclick=()=>modal('데이터 및 이미지 출처','<p>암호화폐: <a href="https://docs.cdp.coinbase.com/exchange/websocket-feed/overview" target="_blank" rel="noopener">Coinbase Exchange 공개 API</a>. USD 마켓 기준이며 국내 거래소 원화 가격과 다를 수 있습니다.</p><p>국내 주식: <a href="https://finance.yahoo.com/" target="_blank" rel="noopener">Yahoo Finance</a>. 국내 주식은 약 20분 지연되며 30초마다 조회합니다.</p><p>코인 심볼: <a href="https://github.com/spothq/cryptocurrency-icons" target="_blank" rel="noopener">Cryptocurrency Icons (CC0)</a>. 코인 브랜드의 식별 목적으로 사용합니다.</p>');
$('export').onclick=()=>{const rows=[['종목','구분','상태','수량','가격 USD','수수료 USD','시간'],...account.history.map(o=>[o.id,o.side,o.status,o.qty,o.price,o.fee,o.time])],blob=new Blob(['\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='nova-orders.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
document.addEventListener('visibilitychange',()=>{if(!document.hidden){refreshDetail();loadCandles()}});renderMarket();renderQuote();renderAccount();showView(location.hash.slice(1)||'trade');resize();refreshStats();refreshDetail();loadCandles();connect();setInterval(status,1500);setInterval(refreshDetail,5000);setInterval(()=>{if(!document.hidden)refreshStats()},60000);

window.addEventListener('hashchange',()=>showView(location.hash.slice(1)||'trade'));
