import{simulate}from './simulation-engine.js';
const coins=[['BTC','비트코인'],['ETH','이더리움'],['SOL','솔라나'],['XRP','엑스알피'],['DOGE','도지코인'],['ADA','에이다'],['LINK','체인링크'],['AVAX','아발란체']];
const stocks=[['005930','삼성전자'],['000660','SK하이닉스'],['005380','현대차'],['035420','NAVER'],['373220','LG에너지솔루션'],['207940','삼성바이오로직스']];
export function mountSimulation(host,market){
 const korean=market==='korea',unit=korean?'KRW':'USD',items=korean?stocks:coins,prefix='sim-'+market;
 host.innerHTML=`<div class="sim-tabs"><button data-view="sim-crypto" class="${korean?'':'active'}">코인 AI 가상투자 시뮬레이션</button><button data-view="sim-korea" class="${korean?'active':''}">국내 주식 AI 가상투자 시뮬레이션</button></div><div class="sim-heading"><span class="eyebrow">SCENARIO LAB / ${korean?'KOREA EQUITIES':'CRYPTO'}</span><h2>한 가지 선택, 300가지 가능성.</h2><p>실제 과거 가격을 바탕으로 투자금의 변화 범위를 탐색하세요.</p></div><div class="sim-layout"><form class="panel sim-form"><h2>시뮬레이션 설정</h2><label for="${prefix}-asset">종목</label><select id="${prefix}-asset" name="asset">${items.map(([id,name])=>`<option value="${id}">${name} · ${id}</option>`).join('')}</select><label for="${prefix}-capital">가상 투자금 (${unit})</label><input id="${prefix}-capital" name="capital" type="number" min="${korean?1000:10}" max="${korean?1000000000:1000000}" step="any" value="${korean?10000000:10000}" required><label for="${prefix}-days">시뮬레이션 기간</label><select id="${prefix}-days" name="days"><option value="5">5${korean?'거래일':'일'}</option><option value="20" selected>20${korean?'거래일':'일'}</option><option value="60">60${korean?'거래일':'일'}</option></select><label for="${prefix}-exposure">투자 비중</label><select id="${prefix}-exposure" name="exposure"><option value="1">100% 투자</option><option value="0.5">50% 투자 · 50% 현금</option><option value="0.25">25% 투자 · 75% 현금</option></select><button class="primary sim-run" type="submit">시뮬레이션 실행</button><p class="sim-error" role="alert"></p><p class="fine">별도의 가상 실험입니다. 내 지갑 잔액이나 보유 종목은 바뀌지 않습니다.</p></form><div class="panel sim-output" aria-live="polite"><div class="sim-empty"><span class="eyebrow">EXPLORE THE POSSIBILITIES</span><h2>결과를 정하지 않은 투자 실험.</h2><p>종목과 투자금을 선택한 뒤 실행해 주세요.<br>수익과 손실이 모두 나올 수 있습니다.</p></div></div></div><details class="panel sim-method" open><summary>계산 방식과 데이터 안내</summary><p>‘AI 가상투자 시뮬레이션’은 과거 일별 수익률을 5일 묶음으로 재추출하는 통계 시나리오 도구입니다. 외부 생성형 AI나 학습된 가격 예측 모델을 사용하지 않습니다. 300개 경로의 중앙값 및 10~90백분위 범위를 보여주며, 이 범위는 미래 가격의 보장 구간이 아닙니다.</p><p>${korean?'국내 주식은 Yahoo Finance의 최근 약 3개월 종가를 사용합니다. 당일 미완료 일봉을 제외하며, 원천 시세는 약 20분 지연될 수 있습니다.':'코인은 Coinbase USD 마켓의 최대 300개 완료 일봉을 사용합니다.'} 한 번 매수 후 보유하고 마지막 날 매도하는 가정이며, 매수·매도에 각각 0.1%의 가상 수수료를 적용합니다. 세금·슬리피지·현금 이자는 제외하며, 국내 주식도 소수점 수량으로 계산합니다. 같은 설정으로 다시 실행해도 표본 추출에 따라 결과가 달라집니다.</p></details>`;
 const form=host.querySelector('form'),output=host.querySelector('.sim-output'),error=host.querySelector('.sim-error'),run=host.querySelector('.sim-run');let result=null,canvas=null;
 const money=n=>new Intl.NumberFormat('ko-KR',{style:'currency',currency:unit,maximumFractionDigits:korean?0:2}).format(n),rate=n=>((n/result.capital-1)*100).toFixed(2)+'%';
 function draw(){if(!canvas||!result)return;const rect=canvas.getBoundingClientRect();if(!rect.width)return;const scale=Math.min(devicePixelRatio||1,2),w=rect.width,h=300;canvas.width=w*scale;canvas.height=h*scale;const ctx=canvas.getContext('2d');ctx.setTransform(scale,0,0,scale,0,0);const b=result.bands,lo=Math.min(result.capital,...b.map(v=>v.low)),hi=Math.max(result.capital,...b.map(v=>v.high)),pad=Math.max((hi-lo)*.15,result.capital*.005),min=lo-pad,max=hi+pad,left=12,right=w-85,top=15,bottom=270,x=i=>left+i/result.days*(right-left),y=v=>top+(max-v)/(max-min)*(bottom-top);
  ctx.font='11px Pretendard,sans-serif';ctx.strokeStyle='#2a362a';ctx.fillStyle='#a0af94';for(let i=0;i<5;i++){const v=min+i*(max-min)/4;ctx.beginPath();ctx.moveTo(left,y(v));ctx.lineTo(right,y(v));ctx.stroke();ctx.fillText(new Intl.NumberFormat('ko-KR',{notation:'compact',maximumFractionDigits:1}).format(v),right+8,y(v)+4)}ctx.beginPath();b.forEach((v,i)=>i?ctx.lineTo(x(i),y(v.high)):ctx.moveTo(x(i),y(v.high)));for(let i=b.length-1;i>=0;i--)ctx.lineTo(x(i),y(b[i].low));ctx.closePath();ctx.fillStyle='#bce77c20';ctx.fill();ctx.save();ctx.beginPath();ctx.rect(left,top,right-left,bottom-top);ctx.clip();ctx.strokeStyle='#85aa6b30';result.paths.forEach(path=>{ctx.beginPath();path.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.stroke()});ctx.restore();ctx.beginPath();ctx.strokeStyle='#c3f06b';ctx.lineWidth=2;b.forEach((v,i)=>i?ctx.lineTo(x(i),y(v.median)):ctx.moveTo(x(i),y(v.median)));ctx.stroke();ctx.lineWidth=1;ctx.setLineDash([4,4]);ctx.strokeStyle='#99a7b0';ctx.beginPath();ctx.moveTo(left,y(result.capital));ctx.lineTo(right,y(result.capital));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#a0af94';ctx.fillText('시작',left,293);ctx.fillText(result.days+(korean?'거래일':'일'),right-35,293);
 }
 new ResizeObserver(draw).observe(output);
 form.addEventListener('input',()=>{result=null;canvas=null;output.innerHTML='<div class="sim-empty"><h2>설정이 변경되었습니다.</h2><p>새 설정으로 시뮬레이션을 실행해 주세요.</p></div>';error.textContent=''});
 form.onsubmit=async e=>{e.preventDefault();if(!form.reportValidity())return;const fields=new FormData(form),asset=fields.get('asset'),name=items.find(x=>x[0]===asset)[1],capital=Number(fields.get('capital')),days=Number(fields.get('days')),exposure=Number(fields.get('exposure'));form.querySelectorAll('input,select,button').forEach(el=>el.disabled=true);run.textContent='과거 데이터 분석 중';error.textContent='';result=null;canvas=null;output.innerHTML='<div class="sim-empty"><h2>실제 과거 가격을 불러오고 있습니다.</h2><p>300개의 가상 경로를 계산합니다.</p></div>';
  try{const url=korean?'/nova/stocks?symbol='+asset+'&period=months':'https://api.exchange.coinbase.com/products/'+asset+'-USD/candles?granularity=86400',res=await fetch(url,{signal:AbortSignal.timeout(15000)});if(!res.ok)throw Error('과거 데이터를 불러오지 못했습니다. 잠시 후 다시 실행해 주세요.');const json=await res.json();const today=korean?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()):null;const bars=(korean?json.bars:json.map(r=>({time:r[0],close:r[4]}))).filter(b=>Number.isFinite(b.close)&&b.close>0&&(korean?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(b.time*1000))<today:b.time+86400<=Date.now()/1000)).sort((a,b)=>a.time-b.time).slice(-300);
   result=simulate({closes:bars.map(b=>b.close),capital,days,exposure});const final=result.bands.at(-1),gain=final.median-capital,start=new Date(bars[0].time*1000).toLocaleDateString('ko-KR'),end=new Date(bars.at(-1).time*1000).toLocaleDateString('ko-KR');output.innerHTML=`<div class="panel-title"><div><span class="eyebrow">SIMULATION COMPLETE</span><h2>${name} · ${days}${korean?'거래일':'일'}</h2></div><span>${unit} · 300개 경로</span></div><div class="sim-metrics"><div><span>중앙 시나리오 평가액</span><strong>${money(final.median)}</strong><small class="${gain>=0?'up':'down'}">${gain>=0?'+':''}${money(gain)} (${rate(final.median)})</small></div><div><span>모의 손실 경로 비율</span><strong>${(result.lossRatio*100).toFixed(1)}%</strong><small>미래 손실 확률을 의미하지 않음</small></div></div><div class="sim-legend">연두선: 중앙값 · 음영: 10~90백분위 · 점선: 시작 투자금</div><canvas class="sim-chart" role="img" aria-label="${name} 가상 평가액 경로. 중앙값 ${money(final.median)}, 10백분위 ${money(final.low)}, 90백분위 ${money(final.high)}"></canvas><div class="sim-range"><div><span>하단 시나리오 · 10백분위</span><strong>${money(final.low)}</strong></div><div><span>상단 시나리오 · 90백분위</span><strong>${money(final.high)}</strong></div></div><p class="sim-insight">${gain>=0?'중앙 경로는 시작 투자금보다 높게 계산됐습니다.':'중앙 경로는 시작 투자금보다 낮게 계산됐습니다.'} 투자 비중은 ${(exposure*100).toFixed(0)}%이며 나머지는 현금으로 유지합니다. 과거 변동의 반복을 가정한 결과로, 새로운 시장 충격과 미래 수익을 예측하지 않습니다.</p><p class="fine pad">사용 데이터: ${start} ~ ${end} · ${bars.length}개 종가 · ${korean?'Yahoo Finance / KSE':'Coinbase Exchange'}<br>표시 범위 밖의 결과도 가능합니다. 실행 결과는 저장되지 않습니다.</p>`;canvas=output.querySelector('canvas');draw();
  }catch(e){error.textContent=e.message||'시뮬레이션을 실행하지 못했습니다.';output.innerHTML='<div class="sim-empty"><h2>분석할 데이터를 기다리고 있어요.</h2><p>연결 상태를 확인하고 다시 실행해 주세요.</p></div>'}finally{form.querySelectorAll('input,select,button').forEach(el=>el.disabled=false);run.textContent='다시 시뮬레이션 실행'}
 };
}
